services:
#  nginx:
#    image: nginx:stable-alpine
#    ports:
#      - "80:80"
#    volumes:
#      - "./nginx.conf:/etc/nginx/nginx.conf"
#    depends_on:
#      - fastapi
##      - frontend
#    networks:
#      - my_network

#my_network  frontend:
#    build:
#      context: ./frontend
#    networks:
#      - my_network

  fastapi:
    build:
      context: ./app
    ports:
      - "8080:8080"
    networks:
      - my_network

  postgres:
    image: postgres:latest
    networks:
      - my_network
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data



networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: