services:
  fastapi:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    working_dir: /app
    image: manchkincards:latest
    volumes:
      - ./backend/images:/app/backend/images
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: