services:
#  nginx:
#    image: nginx:stable-alpine
#    ports:
#      - "80:80"
#    volumes:
#      - "./nginx.conf:/etc/nginx/nginx.conf"
#    depends_on:
#      - fastapi
##      - frontend
#    networks:
#      - my_network

#my_network  frontend:
#    build:
#      context: ./frontend
#    networks:
#      - my_network

  fastapi:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    working_dir: /backend
    depends_on:
      - postgres
    env_file:
      - .env



  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: